# .NET Core pipeline
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azure-devops

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- name: Restore
  task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

- name: Build
  task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- name: Test
  task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- name: Benchmark
  task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    arguments: '--configuration $(buildConfiguration) --project test\UnicornHack.Core.PerformanceTests\UnicornHack.Core.PerformanceTests.csproj --filter * --artifacts $(Build.ArtifactStagingDirectory)'

- name: Publish
  task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    modifyOutputPath: true
    zipAfterPublish: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- name: Upload Artifacts
  task: PublishBuildArtifacts@1
